# Generated by Django 5.0.3 on 2024-03-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_show_alter_contact_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='picture',
            field=models.ImageField(default=True, upload_to='pictures/%y/%m'),
        ),
    ]
